const ACTIONS = {

    // Counter actions types
    INCREMENT: "INCREMENT",
    DECREMENT: "DECREMENT",
    RESET: "RESET",
    ADD_ITEMS: "ADD_ITEMS",
    SET_ITEMS: "SET_ITEMS",
    CLEAR_ALL_ITEMS: "CLEAR_ALL_ITEMS",
    DELETE_ITEM: "DELETE_ITEM",
    EDIT_ITEM: "EDIT_ITEM",

    //Items view actions type
    SHOW_LOADER: "SHOW_LOADER",
    HIDE_LOADER: "HIDE_LOADER",
    SHOW_CLEAR_BUTTON: "SHOW_CLEAR_BUTTON",
    HIDE_CLEAR_BUTTON: "HIDE_CLEAR_BUTTON",
    SHOW_TOAST: "SHOW_TOAST",
    HIDE_TOAST: "HIDE_TOAST",
};

export default ACTIONS;