const ACTIONS = {
  
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  RESET: "RESET",
  ADD_ITEMS: "ADD_ITEMS",
  SET_ITEMS: "SET_ITEMS",
  CLEAR_ALL_ITEMS: "CLEAR_ALL_ITEMS",
  DELETE_ITEM: "DELETE_ITEM",
  EDIT_ITEM: "EDIT_ITEM",

  //Items view actions type
  SHOW_LOADER: "SHOW_LOADER",
  HIDE_LOADER: "HIDE_LOADER",
  SHOW_CLEAR_BUTTON: "SHOW_CLEAR_BUTTON",
  HIDE_CLEAR_BUTTON: "HIDE_CLEAR_BUTTON",
  SHOW_TOAST: "SHOW_TOAST",
  HIDE_TOAST: "HIDE_TOAST",
  TOAST_ORIENTATION_NEGATIVE: "TOAST_ORIENTATION_NEGATIVE",
  TOAST_ORIENTATION_POSITIVE: "TOAST_ORIENTATION_POSITIVE",
  UPDATE_QUERY_STATUS: "UPDATE_QUERY_STATUS",
  UPDATE_QUERY_NAME: "UPDATE_QUERY_NAME",
  CHECK_CHECKBOX: "CHECK_CHECKBOX",
  UNCHECK_CHECKBOX: "UNCHECK_CHECKBOX",
  UPDATE_CHECKBOX: "UPDATE_CHECKBOX",
  UPDATE_DONE_AT: "UPDATE_DONE_AT",
};

export default ACTIONS;
